### PR TITLE
add meson build support

### PR DESCRIPTION
**Pull request by zhuyaliang**
## test meson
```
meson setup _build --prefix=/usr -Din-process=true -Ddefault_library=both

ninja -C _build

DESTDIR=/tmp/meson_dir meson install -C _build
```
## test make
```
 ./autogen.sh --prefix=/usr --enable-in-process=yes

make

make install DESTDIR=/tmp/make_dir
```
## Compare Build Results
```
[test@localhost mate-power-manager]$ find /tmp/make_dir/ | wc -l
489
[test@localhost mate-power-manager]$ find /tmp/meson_dir/ | wc -l
488
```
```meson``` does not provide ```libmate-volume-control-applet.la```, so the total number is one less, which is not a problem

### CODE REVIEW

**Review by lukefromdc — CHANGES_REQUESTED** [review]
Got a major error in the in-process/wayland supporting build: Instead of the applet being named` libmate-volume-control-applet.so`, I got `liblibmate-volume-control-applet.so` while the .desktop file refers to it by the correct name. Thus, the panel cannot find the applet.

This was with these config options:
`meson setup build --prefix=/usr -Dwayland=true -Din-process=true`

 Note that it is currently possible with this code to turn wayland support on yet build the applet out of process, which cannot actually run on wayland. Turning wayland support on should automatically build the applet in-process. Fine to default to out of process for now, as we won't know 100% for a while if those memory corruption/weak pointer issues are all the way fixed. That waits for time and use.

**Comment by zhuyaliang** [comment]
@lukefromdc Please test again

**Comment by lukefromdc** [comment]
Still didn't run in-process, this time the problem was .desktop being appended to the filename of 
/usr/share/mate-panel/applets/org.mate.applets.GvcApplet.mate-panel-applet
which was installed as
/usr/share/mate-panel/applets/org.mate.applets.GvcApplet.mate-panel-applet.desktop
and was thus instantly visible when a known good file dropped in to replace it went in alongside it.
The file itself was OK, verified by cut and pasting its text into the correctly named file. Renaming in Caja didn't work, as .desktop got reappended to the file name that way too.

**Comment by zhuyaliang** [comment]
@lukefromdc The file name has been fixed

**Review by lukefromdc — APPROVED** [review]
Just got a successful build and install in-process with wayland support, tested in both x11 and wayland but only had time tonight for one more test so didn't test out of process.

These build options with a wayland supporting build environment select an in-process applet, and wayland support is then automatic if detected unless turned off. 
` meson setup build --prefix=/usr -Din-process=true`

Ideally, using 

` meson setup build --prefix=/usr -Dwayland=true`

 would automatically select in-process as well but it does not. Instead we get
```
                         project: mate-media 1.27.0
                          prefix: /usr
            Building status icon: true
           Building panel applet: true
             Building in-process: false
                 Wayland support: true
```

Such a build will work fine in x11 but an out of process applet cannot run under wayland. The wayland specific code thus builds but will never be reached at runtime. This however is not something users of the finished packages need ever concern themselves with so I am OK w merging as-is so long as someone on a different system gets a good out of process build. This has been cooking a while and it does work

**Comment by lukefromdc** [comment]
The wrong directory icons I didn't spot, I have another set of icons used from my theme. 

Never once have I seen a meson build install .la files, I've been hand-editing and hand packing these back into GTK and Glib for years. This is a problem when and to my knowledge only when when building a package with autotools that depends on a package built with meson and looks for these files.

**Comment by zhuyaliang** [comment]
@raveit65 The icon issue has been fixed

**Comment by raveit65** [comment]
> `meson` does not provide `libmate-volume-control-applet.la`, so the total number is one less, which is not a problem

Why this isn't a problem?
I mean when someone need this static lib than it is a problem, or not?

**Comment by raveit65** [comment]
Any way, it seems this is meson specific.
I don't mind because i remove the *.la and *.a files since the beginning form packages during the rpm build process for official fedora.

**Comment by raveit65** [comment]
Confirmed that icon dir issue is fixed with latest git push.

**Pull request merged**
