### PR TITLE
applet: make keyboard work in popup

### PR DESCRIPTION
**Pull request by monsta**
fixes https://github.com/mate-desktop/mate-media/issues/94

### CODE REVIEW

**Comment by raveit65** [comment]
review-swap?

**Comment by monsta** [comment]
Yes, but that's not required for the bugfix. Do you want it here too?

**Comment by raveit65** [comment]
Well, better we fix it now instead of touch the same code later again ;-)

**Comment by monsta** [comment]
I can do it, but I think it should go in a separate commit as it will add some more complexity.

**Comment by lukefromdc** [comment]
I agree: these are two separate issues best handled separately.  I advise merging this now as it works, rather than holding it pending the other issue.

**Comment by raveit65** [comment]
Another commit can also be done in this PR.
...well, it's only a comment from me not a review.

**Comment by monsta** [comment]
Merged and added https://github.com/mate-desktop/mate-media/pull/100 for GdkSeat stuff.

**Comment by raveit65** [comment]
That works!

**Pull request merged**
