### PR TITLE
Use different icon for pulseaudio monitor inputs vs mic inputs

### PR DESCRIPTION
**Pull request by lukefromdc**
Use a new set of four icons audio-input-monitor (muted, low, medium, high) instead of the microphone icons for Pulseaudio monitor inputs. Used code by https://github.com/ajorg-aws to tell them apart, and code copied from gvc-stream-status-icon.c to update the newly selected icon for volume level when a recording session is started or the input is switched between monitor and microphone

### CODE REVIEW

**Comment by lukefromdc** [comment]
An alternative to https://github.com/mate-desktop/mate-media/pull/111 that retains the ability to use the input slider with a monitor input, by showing an icon of two jack plugs on a U-shaped cable.

Still need a way when switching back to the microphone or starting the mic to get the icon to update before the slider has been opened. That also would allow showing a muted monitor input when it is muted, with one more icon

**Comment by raveit65** [comment]
How, can i test this?
I don't use a microphone normally but i have a headset.
Detailed instructions please?

**Comment by raveit65** [comment]
I have a normal 7.1 sound card from my motherboard but no mic, only a headset which is a usb sound card in the end.
The icon in na-tray i noticed when i am firing up a VM.

**Comment by raveit65** [comment]
I got some build warnings.
```
gvc-applet.c:90:30: warning: unused variable 'markup' [-Wunused-variable]
         gchar               *markup;
                              ^~~~~~
gvc-applet.c:86:30: warning: unused variable 'decibel' [-Wunused-variable]
         gdouble              decibel = 0;
                              ^~~~~~~
```

**Comment by raveit65** [comment]
For some reasons i need to fire up always a VM and choose `Internal analog stereo` in volume control setting of the guest, to make the icons in na-tray of host box visible. :open_mouth: 
But this is also without PRs and unrelated to new code.

Personal i think we should drop most of mate-media code.
In the end we need only an applet with a slider for master volume, which opens pavu-control (pulseaudio sound control)
They have more resources to support all kind of audio hardware.
And we have enough open issues which aren't fix.
E.g switching audio source between main audio device and headsets, which works out of box with pavu-control.

**Comment by lukefromdc** [comment]
Closing in favor of https://github.com/mate-desktop/mate-media/pull/111 due to simplicity vs feature bloat issue, and due to ongoing GtkStatusIcon bugs affecting the tray. Keeping a built package of this around for testing GtkStatusIcon/system tray experiments...

**Pull request closed without merging**
