### PR TITLE
man/: mate-volume-control-applet.1 -> mate-volume-control-status-icon…

### PR DESCRIPTION
**Pull request by sunweaver**
….1. (Binary got renamed, man page had been forgotten).

### CODE REVIEW

**Comment by lukefromdc** [comment]
As of now, we have both the status icon AND a panel applet. This PR renames the manpage file to apply only to the status icon. Do we want to do this given that some user might not then be able to find the manpage? Alternately do we want to install manpages for both the status icon and applet?

**Comment by raveit65** [comment]
> Do we want to do this given that some user might not then be able to find the manpage? Alternately do we want to install manpages for both the status icon and applet?

Fedora use the panel applet. So from my point of view the status-applet has reached EOL.

**Review by lukefromdc — APPROVED** [review]
Approving as this works and is technically correct. The existing manpage is INCORRECT for the applet, as
` mate-volume-control-applet --help `
does NOT work (no such application, its a panel applet) and 
`mate-volume-control-status-icon --help`
DOES work
Therefore we need to make this change too. Only issue is will user know to look for the manpage under the new name, ideally distros would include that in their release notes-and this would go in the release notes for MATE 1.26

**Review by raveit65 — COMMENTED** [review]
LGTM

**Pull request merged**
