### PR TITLE
Clang analyzer

### PR DESCRIPTION
**Pull request by yetist**
deploy github pages

### CODE REVIEW

**Comment by sc0w** [comment]
I see no html reports in https://mate-media.mate-desktop.dev

**Comment by sc0w** [comment]
mate-media has no clang analyzer bugs, and I can add one argument to force travis to fail if it detects bugs, and I can do the same in repositories without bugs

@mate-desktop/core-team 

I need to know if you are agree

**Comment by raveit65** [comment]
Really?
Why should the build fail when clang reports an issue?
Than most builds will fail only because of clang.
In result i can't approve a review because of a clang warning.
I mean clang is useful, but it isn't the main reason why we use travis-CI.

**Comment by sc0w** [comment]
> Why should the build fail when clang reports an issue?

This will improve the workflow for me, if travis is ok, clang analyzer is ok and there is no reason to see the .dev page with analyses

> Than most builds will fail only because of clang.

I suggest to do that **only** in repos without bugs (like mate-media)

Please don't panic, it was a suggestion, if you aren't agree, no problem :)

**Comment by raveit65** [comment]
>> Why should the build fail when clang reports an issue?

> This will improve the workflow for me, if travis is ok, clang analyzer is ok and there is no reason to see  the .dev page with analyses

Without any panic, only pure realistic, how do want filter out clang false positives?
I recall that there were some in the last 2 months in some of your PRs.
And i am not the person who can evaluate a fault positive error/warning.

> I suggest to do that **only** in repos without bugs (like mate-media)

This sounds better.

**Comment by sc0w** [comment]
yes, the problem are the false positive warnings

**Pull request merged**
