### PR TITLE
[ci] Enable Clang Static Analyzer

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by raveit65** [comment]
I enabled gh-pages.

**Comment by raveit65** [comment]
There is a build issue.
```
+ new_result=@cd1c6049b74d_clang-analyzer
+ mv html-report/ html-report/@cd1c6049b74d_clang-analyzer
mv: cannot move 'html-report/' to a subdirectory of itself, 'html-report/@cd1c6049b74d_clang-analyzer'
!!! ERROR: run command [docker exec -t mate-media-fedora-build /rootdir/after_scripts].
The command "./docker-build --name ${DISTRO} --verbose --config .travis.yml --build scripts" exited with 1.
```

**Comment by yetist** [comment]
Fixed by https://github.com/mate-desktop/mate-dev-scripts/pull/20

**Comment by raveit65** [comment]
Thanks it is working now.

**Comment by raveit65** [comment]
Hmm, i am still wondering about the result `hi`.

**Comment by raveit65** [comment]
@yetist 
Are you sure that all is working correct?
In this test PR i got same weird result page.
https://github.com/mate-desktop/mate-media/pull/123

**Comment by yetist** [comment]
Sorry, I wrote two `deploy` sections in the `.travis.yml` file, the the first one is ignored.
New PR to fix that: #124

**Pull request merged**
