### PR TITLE
Support custom volume control themes

### PR DESCRIPTION
**Pull request by lukefromdc**
Support custom volume control themes, including robust support for transparent themes. Both panel slider and menu can be themed. Menus follow the same selectors as the newly merged mate-panel theme support. The pair of selectors below create a transparent black slider, this method is needed so that the brightness applet in mate-power-manager can also be controlled. The volume control is coded as a frame inside a frame, but the brightness applet is coded as a single frame.

 .mate-panel-menu-bar .frame{ 
	background-color: alpha(black, 0.8);
	border-image: none;
	border-style: solid;
	border-color: #888a85;
	border-width: 2px;
	border-radius:6px;
	padding: 0px;
	margin: 0px;
}

.mate-panel-menu-bar .frame .frame{ 
	background-color:transparent;
	border-image: none;
	border-style:none;
	border-radius:0px;
	padding: 0px;
}

This package was selected to be my next PR because there is only one commit plus three "keep-up" merges from upstream master to worry about, and because the volume control is always present in a default layout.

### CODE REVIEW

**Comment by raveit65** [comment]
Seems to be working, but real transparency does not work here.
I see the bg color of the panel itself under the alpha color.
The bg color of the panel i have set with the 
.mate-panel-menu-bar {
}
selector. ie. https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L344
So , i'm still wondering how real transparency does work with your theme.

But i'm not willing to use 'git rebase' on your PR again.
- please do not use the word Hack
- indents are worse and different from the rest of the code.
In general we prefer to use blanks and not tabs, but this depends on the code area.
New code should use the same style like the code where you want to include it.
- merge commits from upream are there because you didn't use a another branch
A branch you can create on Webpage in browser, click on the branch button.
I suggest to fix this all and start a new PR from a different branch.
Sorry, don't think i'm petty but we like a good looking code in git.
In general your PR looks good.

**Comment by lukefromdc** [comment]
I had no idea what your objections were even about until now. That 
"hack" tag was orignally for my own use so I could quickly find it, nothing
more. I am happy to remove it from the code.  I do not see what you 
wanted done in rebasing this however. 

Feel free to close this PR, as you are asking me to so something I have 
made zero progress on in a week of attempts. As long as nobody objects
to my having my own fork here for my own use, that is good enough and I
will stick to that.  All I can offer right now is these branches, or patch files 
made from them. 

Unfortunately I still get nothing but errors when trying to do anything from
the git command line beyond a "clone" or "pull."  I get errors about the 
repo being invalid or not able to be found or some such thing. I am on the 
verge of throwing in the towel on this.

I have also not been able to make new clean forks from mate-panel/master
using the website, which would have enabled me to make new commits and 
immediately offer them as PR's.

**Comment by raveit65** [comment]
Creating a branch where you can fire up PRs is easy, not git command needed.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/create-a-branch.ogv

**Comment by lukefromdc** [comment]
That I know how to do and have done, but it makes a branch of my own fork containing all changes to date.  What I need is a new branch from mate-desktop/master for a do-over, a "manual rebase."  Anyway to do this other than delete the whole repo and fork it anew?

**Comment by raveit65** [comment]
OK,
on your box, after you created the new branch-
git pull
git checkout your-new-branch  --> switching to new branch
normaly you can use 'git rebase -i', but that's to complicated to explain.
Use hard reset to reach to a commit before you started to commit, this avoids revert commits.
reset the last commit:
git reset HEAD^ --hard
git push -f
Repeat that until you are at your target.
Or see http://lrotherfield.com/blog/delete-remote-git-repo-to-specific-commit/
Note: using hard reset should not be done on repos which are cloned fom other ppls.

**Comment by lukefromdc** [comment]
I have not been able to get ANY command line interaction to work other than
"clone" or "puil" on anything, If this cannot be continued without getting past that
obstacle, let's put this PR on indefinate hold or close it. 

Is it OK to delete my entire repo and make a new one, apply my change, make
a branch of that just for the PR, and submit a new PR? At this point I think I must
choose between the history in the exisitng repo and the PR, I don't know if it has
any other users or not.

**Comment by lukefromdc** [comment]
This PR is now invalid as the branch it was made from has been deleted and replaced. A new fork was made, a branch of that was made, and the theming changes committed to it in a single commit. Built and tested it, then branched again, the PR coming from that branch, The new PR is 
https://github.com/mate-desktop/mate-media/pull/69

**Pull request closed without merging**
