### PR TITLE
Convert GtkStatusIcon to real applet

### PR DESCRIPTION
**Pull request by lukefromdc**
GtkStatusIcon is deprecated, our own applets are not

### CODE REVIEW

**Comment by lukefromdc** [comment]
With my single large .svg icon (for sharpness in the OSD), I got the icon rendering rather small, while it uses full panel height with the GNOME/MATE icons. Also, on iterating through panel heights I got some instances of icon cutting like what we had with the weather icon in the clock. I will play with that, should be an easy fix.

Also, wondering how hard it would be to convert this to a vertical slider, possibly by adding an orientation option to gvc_channel_bar ? I will take a look at that as well.

This is majorly the way to go however

**Comment by lukefromdc** [comment]
My own commit
https://github.com/mate-desktop/mate-media/pull/118/commits/b066167a475fe7d152ed0660c349ea3492f60965
stops the mate/gnome/ContrastHigh icons from cutting at any panel size, is the same fix used before for the weather icon in mate-panel's clock.

Still get undersize icons in my own theme which at the moment is providing only a large, high-resolution scaleable icon so as not to have the OSD pick up smaller ones. If I can't fix that here I can change it in my icon theme

mate_panel_tiny_sound_icon

**Comment by lukefromdc** [comment]
Oh yeah: icon themes do have to provide icons in the individually sized directories or for some reason none of the functions for determining icon size work. With GtkStatusIcon this information came from the tray and for whatever reason worked without regard for this icon directory issue. 

If we don't know of any other icon themes than mine that only provide a single icon size (e.g only a symbolic icon), than we can merge this without creating icon size issues, as I can easily fix my own theme.

**Comment by lukefromdc** [comment]
Keeping these commits separate (can squash later) in case we want to revert any of them for any reason

**Comment by lukefromdc** [comment]
Also just found top panel gives a vertical slider, only a bottom panel gives a horizontal slider

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-media/pull/118/commits/2eed609e07e2e2a4aafd629e927b993385853629 takes care of the single directory of .SVG icons case, such as my theme or any symbolic icon theme that might be forced from a GTK theme.

volume_icon_fixed

**Comment by lukefromdc** [comment]
The horizontal slider on a bottom panel, and inconsistant orientations of the slider popped up from a vertical panel seem to be inconsistant data being passed to 
```
gvc_stream_status_icon_set_orient (GvcStreamStatusIcon  *icon,
                                   MatePanelAppletOrient orient)
```
in gvc-stream-status-icon.c from in gvc-applet.c 
```
static void
gvc_applet_set_orient(GtkWidget *widget, MatePanelAppletOrient orient, gpointer user_data)
{
        GvcApplet *applet = user_data;

        gvc_stream_status_icon_set_orient (applet->priv->icon_input, orient);
        gvc_stream_status_icon_set_orient (applet->priv->icon_output, orient);
}
which is turned is called from a gsignal in this from in gvc-applet.c :
```
        /* Update icons on size/orientation changes */
        g_object_connect (applet->priv->applet,
                         "signal::change_size", gvc_applet_set_size, applet,
                         "signal::change_orient", gvc_applet_set_orient, applet,
                         NULL);
```

```

**Comment by lukefromdc** [comment]
We also lost the mute functions, and picked up this related build warning:
```

At top level:
gvc-applet.c:421:1: warning: ‘menu_output_mute_toggle’ defined but not used [-Wunused-function]
 menu_output_mute_toggle (GtkAction *action, GvcApplet *applet)
 ^~~~~~~~~~~~~~~~~~~~~~~
gvc-applet.c:414:1: warning: ‘menu_input_mute_toggle’ defined but not used [-Wunused-function]
 menu_input_mute_toggle (GtkAction *action, GvcApplet *applet)

```

**Comment by vkareh** [comment]
Yeah, that last piece of code there (the orient callback) I need to rework a bit. Ultimately, I want to decouple the gvc_stream from the MatePanelApplet entirely. It also means that we would be able to use either the GtkStatusIcon or the Applet (or both if the user wanted that)

**Comment by vkareh** [comment]
The mute gave me a lot of trouble, since the context menu is at the applet level, but the mute is at the stream level, so if you mute the stream (like using a key or middle click) the toggle button doesn't get updated. So that part definitely needs work

**Comment by vkareh** [comment]
Thanks for testing this, btw :)

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-media/pull/118/commits/1a3767a956d5c70a422483ace805506152a70491
Keeps the volume slider perpendicular to the panel. Apparently there is an issue with retrieving the applet orientation on bottom panels. All that's left is to pack the "mute" item back into the menu, muting by right-click works.

**Comment by lukefromdc** [comment]
If you've got a better way to handle the orient than what I did, feel free to push it and I will test again. Meanwhile to have a crack at that menu

**Comment by lukefromdc** [comment]
I was able to get the mute items working (tested output) and the only problem so far is as you mentioned the checks don't update. I will see if I can find a way to get that to work

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-media/commit/8aa0ecf2ac5289fa02d91ea5d8de5ce2ed81a8df
to separate WIP branch https://github.com/mate-desktop/mate-media/tree/convert-to-applet-w-mute-WIP brings back mute menuitems and makes them mostly work. They will always unmute a muted input/output regardless of how it was muted or unmuted, but the labels and icons (which change with this status) only track changes set from the menu.

At this point we have three reasonable options I can see:

1: Dump the active menuitems and instead pack in an inactive label telling users to use the middlemouse for mute. Muting and unmuting an input though would be impossible without either media keys, a custom keybinding, using something like alt-middlemouse (if that's even possible) to mute/unmute inputs. Simple but a feature loss for users compared to the tray applet.

2: bring back the icons I proposed earlier for monitor inputs so anything muted has an appropriate icon, then use unchanging "Mute Input" and "Mute Output" labels and icons.  This should be a bit more reliable with GtkStatusIcon out of the picture, and entirely reliable when in the future all applets are ported to in-process for wayland and Xembed, GtkPlug, and GtkSocket are entirely out of the picture.

3: Find a way to connect the changing and descriptive icons and text to a signal sent whenever the input or output is muted. We would need to send a signal from gvc-stream-status-icon.c and catch it in gvc-applet.c and get the GvCApplet into the function catching the signal. That way, anything muting or unmuting an input or output causes the correct text and icon to display the next time the menu is popped up.

As it stands now in the WIP branch, the code that mutes or unmutes from the menu also resets the menuitem for the next time, but that only works from the menu.

**Comment by raveit65** [comment]
Here, mute did work out of box with middle mouse-click. I used only the first initial commit.
Same like it was before.
bildschirmfoto zu 2019-02-08 11-36-50
Well, i didn't check build logs.
Edit:
Got it, you meant the menu-entries.

**Comment by lukefromdc** [comment]
One approach that does work is this: simple menuitems for mute without icons (so they don't compete with muted or unmuted "status" icons), plus showing an icon set for monitor inputs so we always have something that can be shown muted or not. Not the ideal way but it does work:

https://github.com/mate-desktop/mate-media/commit/5034b885eb714ba1d0b7cd174a6337ef5f4ae625
from new branch https://github.com/mate-desktop/mate-media/tree/convert-to-applet-mute-simple-WIP

**Comment by raveit65** [comment]
Not sure if it makes sense to mute the Input, as you can only mute the summary of all inputs of an recording, which can be one or several inputs together.
Muting Inputs makes only sense for me if you can mute a single input of a recording, let say 1 of 4 for example, and input 2/3/4 is running.
But this is more an extended configuration which belongs in the mixer GUI and not in a menu of an applet.
IHMO, muting only the output is sufficient, same like it was before.

**Comment by lukefromdc** [comment]
I will simplify the mute functions today, and take another crack at detecting the menu popup so it can be updated to allow showing mute status(that one's a maybe). A use-case for this, BTW, is Wayland, once all applets are ported to in-process.

**Comment by lukefromdc** [comment]
I just force-pushed the https://github.com/mate-desktop/mate-media/tree/convert-to-applet-mute-simple-WIP branch to https://github.com/mate-desktop/mate-media/commit/764232c5ba8eb876ea3ba814d14b77f1034538ef which shows a "Mute/Unmute Output" menu item and does away with showing a monitor input icon and slider. 

Anything that could be done with those can be done with the output anyway when recording the output, so that was redundent and added needless complexity.

**Comment by lukefromdc** [comment]
Added the "Mute/Unmute Output" menitem to this PR as its simple and works, as simplifies tracking all this.  We have time, as none of this can be merged to master until 1.22 is out and master has been version-bumped to 1.23

**Comment by lukefromdc** [comment]
I have found that there is no way to connect a gsignal from the menu (popped up with gtk_menu_popup_at_widget), nor a gsignal from icon_output to GvcApplet, and without that there is no way to get a menuitem to change its appearance in response to being muted elsewhere. I don't know how to signal cross-instance or cross-process with dbus, and without that what I have now for a mute menitem is the best I can do.  Again, we will need this for wayland if nothing else.

**Comment by lukefromdc** [comment]
I finally managed to find a way to make the mute menuitem track mute state, changing text and icon between "Mute Output" and "Unmute Output" by piggybacking on an existing callback connected by `g_object_connect` and making the code work there, then moving it to a new callback and finding another signal. `event-after` worked, by causing the callback to update the menu to get called everytime the user clicks the button to bring up the menu without swallowing the click like "event" or button-press-event would, nor delaying like button-release-event did and missing keyboard mute/unmute. 


Tested with menu, middlemouse, and media key muting and unmuting, got absolutely consistant results. Could NOT use a toggle menu item though, because sometimes it took two clicks to change a mute status, much as it did when first tested. Had to implement that directly, and don't have a good "check" icon (and an added one would never match all GTK themes) so just used speaker mute and middle volume icons.

**Comment by raveit65** [comment]
> ...........We have time, as none of this can be merged to master until 1.22 is out and master has been version-bumped to 1.23.

> Edit-unless of course @raveit65 wants all or part of this for Federa F30 as per [aba289d#comments](https://github.com/mate-desktop/mate-media/commit/aba289d52f10f16be96d4093ca891bd65abdb8d8#comments)

If it is ready i will use it for fedora 30.
In opposite to other distros i have all freedom of the world and i can use it as patches on to top of 1.22 or 1.20 ;)
I am not sure about adding it to already released fedora versions, because the old applet is in /etc/XDG/autostart/ folder and this needs to be disabled.
This can be problematic if a user had change the autostart behaviour and the applet is in ~/.config/autostart/ .

For me the question is more if we want to keep the old applet?
When keeping the old applet beside of the new one, than integration to an existing installations is seamless.
An user with a HIDIPI monitor, or if you want to use it for other reasons, only needs to enable the new applet and disable the old one from autostart.
And normal behavior won't be changed.

That means, if we can keep the old applet than this can be consider as bugfix for HIDPI support, and can be back ported to a stable branch, IHMO     ;)

**Comment by raveit65** [comment]
Mute/Unmute from menu is working fine now.
The entry will also be changed if i use my infrared remote control to mute the output volume.
I guess the commits for muting the volume can be squashed together, or not?

**Comment by raveit65** [comment]
Would be nice to have `accels` for the mute menu entry, same like the other entries.
Than it's easier to use with a keyboard.

**Comment by lukefromdc** [comment]
I will see if I can get an accel onto the mute entry, probably by cribbing code from the preferences entry. Then I will squash all the menu stuff

**Comment by lukefromdc** [comment]
Right now I see keyboard accels in Pluma, Caja, and even Firefox but none in any menus from mate-panel, in any theme.

**Comment by lukefromdc** [comment]
I just rebased to clean up the commit history, and in the process cleaned up two unused variables and a wrong initial name/no icon config for the mute menuitem that nobody would ever see because of the updater function.  

I put all the volume icon size stuff into a single commit, and all the mute menuitem stuff into another single commit, keeping the overall history separate for now.

I experimented with trying to get keyboard accels into the menu but it didn't work. While the Gtk docs for GtkActionEntry
https://developer.gnome.org/gtk3/stable/GtkActionGroup.html#GtkActionEntry
specify that both accelerators and tooltips can be added (in the places we have NULL, first accel and then tooltip if desired), for some reason neither one would actually work in the applet menu. I wonder if that is a limitation imposed somewhere in MatePanelApplet itself, as the exact same code is used in Caja and works fine there, showing GTK is not the culprit here. 

In fact, I noticed I don't have any menuitem accels anywhere in any menu that can be popped up from the panel. If we get this fixed, the next problem would be that keyboard accels work when the menuitem is NOT showing or at least not popped up by mouse. We already have the media mute key as the default keyboard shortcut to mute and unmute the output, but users without media keys might change that shortcut. NULL is supposed to show a "default" accel but I am not sure if that means no accel or the existing keyboard shortcut matching the action the menuitem triggers. The latter would be really nice, but of no use here if MatePanelApplet has an issue keeping accels off all panel menus

**Comment by vkareh** [comment]
@raveit65 @lukefromdc - I've taken the original files that provided the status-icon and renamed them from `*applet*` to `*status-icon*` (I've also renamed the structs inside). This way we can have both the MatePanelApplet and the GtkStatusIcon running simultaneously, so any user/distro can decide what to use.

**Comment by raveit65** [comment]
Amazing, i have 2 applets :)
Bildschirmfoto zu 2019-03-09 22-49-01

**Comment by lukefromdc** [comment]
I just retested this, both the status icon and the panel applet work great, and can in fact be both run at the same time for testing purposes. Migration should be simple: uncheck "volume control" in m-c-c->startup applications, then add the panel applet to the panel. This gives a fix for hidpi users and ideally would be documented somewhere, perhaps the 1.24 release notes if nowhere else.

Also can be ported to wayland like the rest of the panel applets by porting (all of them) to in-process in the future, as GNOME already did for gnome-panel. Lots easier than creating a wayland implementation for GtkStatusIcon from scratch.

**Comment by sc0w** [comment]
which are the benefits of this PR?

It still have deprecated GtkStatusIcon

or it can be disabled in the build?

**Comment by lukefromdc** [comment]
It is the HiDPI consideration that created the orignal reason for this PR as I recall. The deprecation of GtkStatusIcon was why we were not expecting GNOME to fix the blurry icons with more work on deprecated  GtkStatusIcon.

Benefits of the PR are that the tray applet gives clear, sharp resolution on HiDPI displays. Also that it can be (with a second round of work to port the applet to in-process) ported to wayland while GtkStatusIcon cannot be.

We could use this in MATE 1.24 and deprecate the status icon version ourselves, suggesting users switch to the tray applet  and stating that beginning with MATE 1.26 only the tray applet will be available. The main reason given for adding back the status icon option was for reasons of migration.

A configuration switch to turn off the deprecated status icon does give distros another option, not sure if that effort is actually needed though. GNOME is not removing GtkStatusIcon from GTK3, but it will never be available in Gtk4, cannot be made to work in Wayland as it uses Xembed, and unless GTK devs choose to work on it some more will never give sharp icon display on HiDPI displays.

**Comment by raveit65** [comment]
> or it can be disabled in the build?

Might be a good idea to have configure options for it. (--enable-status-icon-applet, --enable-panel-applet)
This will improve the integration much more.
@vkareh @lukefromdc 
I guess there is only one file for one applet in code, right?


@sc0w 
> which are the benefits of this PR?

See, my screenshot, there you can see how ugly GtkStatusIcons are looking with HIDPI resolution.
They are blured. (blueberry-applet, dropbox-applet, mate-display-applet, nm-applet)

**Comment by raveit65** [comment]
> A configuration switch to turn off the deprecated status icon does give distros another option, not sure if that effort is actually needed though.

Currently the old applet will always be installed. With --enable/disable-status-icon-applet a distro maintainer can force the usage of the panel-applet.
Of course the applet needs to be added to panel layout file. Under https://github.com/mate-desktop/mate-panel/tree/master/data

**Comment by vkareh** [comment]
> I guess there is only one file for one applet in code, right?

They are now split into their own files, so each applet can be built independently. Adding a flag should be trivial at this point.

**Comment by lukefromdc** [comment]
Latest commit allows disabling either the panel applet or the status icon but not both in configuration. Default is to build both, and four permutations of build flags have been tested (none(default)(builds both) , `--enable-panelapplet=no  --enable-statusicon=yes`(builds only status icon) ,` --enable-panelapplet=yes --enable-statusicon=no`(builds only panel applet) and `--enable-panelapplet=no  --enable-statusicon=no`(configuration error out, warns that one or the other must be built).

**Comment by vkareh** [comment]
@lukefromdc - thanks, this works really well! I think we have everything we need to merge this :)

**Comment by raveit65** [comment]
We need to disable building mate-volume-control-applet.desktop from autostart dir, when GtkStatusIcon won't be build.
https://github.com/mate-desktop/mate-media/blob/master/data/Makefile.am#L9

**Comment by raveit65** [comment]
Should we consider this as bugfix for HIDPI and merge it to 1.22 branch?

**Comment by vkareh** [comment]
Not sure, it might break things if distros don't update their build files... It _is_ technically a breaking change :/

**Comment by raveit65** [comment]
But 1.22 isn't in any stable repo from distros.
Fedora 30 isn't releases and ubuntu has only a playground repo with 1.22 (hopefully).
So i am i doubt that we break something?
And official 1.22 release was 2 days ago.

Well, i can patch mate-media for fedora 30/29/28.

**Comment by vkareh** [comment]
that's a good point. I'm okay cherry-picking this for 1.22

**Comment by raveit65** [comment]
Thanks guys, this was a perfect example of team work :)
Maybe we can do the same for mate-display-applet?

**Comment by lukefromdc** [comment]
Oh yeah-that's the other thing we have in MATE that now only uses GtkStatusIcon. Once both of these are fixed, any distro building mate-polkit with SNI support only needs the legacy tray to support 3ed party application's tray icons, of which there are still a lot.

**Comment by lukefromdc** [comment]
Caja's tray icon for extended file copy jobs is another problem. We can live with that being blurry in hidpi (and thus keep using GtkStatusIcon and the traditional tray for this),  find a way use the new notification for the same function (keep it showing, use it to hide and show the file replacement dialog), or port it to a tray icon and find a way to prompt users to install it.  In SNI we would have to open first a menu, then offer to show the dialog from that menu. A panel applet would be possible but it would have to be added to the panel In fact, the status icon for the display also is offered to be added from the m-c-c display capplet. We could replace that with text suggesting adding the applet when that is written, we could also have an item in Caja preferences suggesting a "file management" panel applet.

Simplest for that might be to just make the file copy dialog window unclosable unless all jobs have been cancelled but let it be minimized to the window list, and show it on all desktops. Then the window list itself is doing the job of the tray icon.

Unless GTK devs decide to fix the HiDPI issues with GtkStatusIcon (unlikely), the growing popularity of HiDPI displays may effectively enforce GNOME's deprecation of it.

**Pull request merged**
