### PR TITLE
panel-applet: ensure speaker can be shown alongside or above mic

### PR DESCRIPTION
**Pull request by lukefromdc**
Initialize the applet GktBox in the appropriate direction.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Mostly fix https://github.com/mate-desktop/mate-media/issues/154 

Previously we were unconditionally packing icons into the box horizontally no matter what the panel orientation. This kicked the speaker icon out of a vertical panel in favor of the microphone icon for lack of space. Initializing the box vertical on a vertical panel causes the icons to pack vertically in that case. For a horizontal panel we keep the horizontal orientation.

Note that trying to use gtk_orientable_set_orientation to reset the box orientation after it has already been set up did not work, possibly because icons had ever already been packed into the box. 

Doing this at initialization works, but if the applet is dragged from a vertical panel to a horizontal one or vice-versa the panel must be restarted or the applet removed and added back to get both icons to show up. Same if the whole panel is changed from horizontal to vertical or vice-versa.

We also have another orientation change issue with this applet, the cpufreq applet, and the sensors applet: they are not updating their backgrounds when the panel is changed from horizontal to vertical or vice-versa.

**Comment by lukefromdc** [comment]
Travis caught an error where the change pushed did not match the change to the file built, due to an accidental change just before copying from the build directory back to the git repo directory(in which I never build).

**Comment by lukefromdc** [comment]
Merging as we have a huge number of open PR's right now and reviewers are overwhelmed so another review might not be likely

**Comment by cmadamsgit** [comment]
I'm a little late (was travelling and didn't catch up), but I can also confirm this works on Fedora 31, as applied to the mate-media-1.22.2 SRPM. Thanks for the quick fix!

**Pull request merged**
